/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

/**
 *
 * @author User
 */
public class NhaXBvsCC extends javax.swing.JPanel {

    /**
     * Creates new form NhaXBvsCC
     */
    public NhaXBvsCC() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        Jbody = new javax.swing.JPanel();
        jScrollPane6 = new javax.swing.JScrollPane();
        jTable6 = new javax.swing.JTable();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        rdbHDNXB2 = new javax.swing.JRadioButton();
        rdbUnHDNXB2 = new javax.swing.JRadioButton();
        txtSDTNXB4 = new javax.swing.JTextField();
        jLabel28 = new javax.swing.JLabel();
        txtDiachiNXB4 = new javax.swing.JTextField();
        jLabel29 = new javax.swing.JLabel();
        txtTenNXB2 = new javax.swing.JTextField();
        btnCleanNXB2 = new javax.swing.JButton();
        btnInsertNXB2 = new javax.swing.JButton();
        btnUpdateNXB2 = new javax.swing.JButton();
        jLabel30 = new javax.swing.JLabel();
        txtTenNCC2 = new javax.swing.JTextField();
        txtDiachiNXB5 = new javax.swing.JTextField();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        txtSDTNXB5 = new javax.swing.JTextField();
        jLabel33 = new javax.swing.JLabel();
        rdbHDNCC2 = new javax.swing.JRadioButton();
        rdbUnHDNCC2 = new javax.swing.JRadioButton();
        btnInsert6 = new javax.swing.JButton();
        btnUpdate6 = new javax.swing.JButton();
        btnClean6 = new javax.swing.JButton();
        btnDelete6 = new javax.swing.JButton();
        jScrollPane9 = new javax.swing.JScrollPane();
        tblNCC2 = new javax.swing.JTable();

        setLayout(new java.awt.BorderLayout());

        Jbody.setBackground(new java.awt.Color(255, 255, 255));

        jTable6.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Tên Nhà Xuất Bản", "Địa Chỉ", "Số Điện Thoạii", "Trạng Thái"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane6.setViewportView(jTable6);

        jLabel26.setText("Trạng Thái");

        jLabel27.setText("Số Điện Thoại");

        rdbHDNXB2.setText("Đang Hoạt Dộng");
        rdbHDNXB2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdbHDNXB2ActionPerformed(evt);
            }
        });

        rdbUnHDNXB2.setText("Đang Ẩn");
        rdbUnHDNXB2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdbUnHDNXB2ActionPerformed(evt);
            }
        });

        txtSDTNXB4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSDTNXB4ActionPerformed(evt);
            }
        });

        jLabel28.setText("Địa Chỉ");

        txtDiachiNXB4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDiachiNXB4ActionPerformed(evt);
            }
        });

        jLabel29.setText("Tên Nhà Xuất Bản");

        txtTenNXB2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTenNXB2ActionPerformed(evt);
            }
        });

        btnCleanNXB2.setText("Mới");

        btnInsertNXB2.setText("Thêm");

        btnUpdateNXB2.setText("Sửa");
        btnUpdateNXB2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateNXB2ActionPerformed(evt);
            }
        });

        jLabel30.setText("Tên Nhà Cung Cấp");

        txtTenNCC2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTenNCC2ActionPerformed(evt);
            }
        });

        txtDiachiNXB5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDiachiNXB5ActionPerformed(evt);
            }
        });

        jLabel31.setText("Địa Chỉ");

        jLabel32.setText("Số Điện Thoại");

        txtSDTNXB5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSDTNXB5ActionPerformed(evt);
            }
        });

        jLabel33.setText("Trạng Thái");

        rdbHDNCC2.setText("Đang Hoạt Dộng");
        rdbHDNCC2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdbHDNCC2ActionPerformed(evt);
            }
        });

        rdbUnHDNCC2.setText("Đang Ẩn");

        btnInsert6.setText("Thêm");
        btnInsert6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInsert6ActionPerformed(evt);
            }
        });

        btnUpdate6.setText("Sửa");
        btnUpdate6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdate6ActionPerformed(evt);
            }
        });

        btnClean6.setText("Mới");

        btnDelete6.setText("Xóa");

        tblNCC2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Tên Nhà Xuất Bản", "Địa Chỉ", "Số Điện Thoạii", "Trạng Thái"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane9.setViewportView(tblNCC2);

        javax.swing.GroupLayout JbodyLayout = new javax.swing.GroupLayout(Jbody);
        Jbody.setLayout(JbodyLayout);
        JbodyLayout.setHorizontalGroup(
            JbodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JbodyLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(JbodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(JbodyLayout.createSequentialGroup()
                        .addGroup(JbodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(JbodyLayout.createSequentialGroup()
                                .addComponent(jLabel33, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(52, 52, 52))
                            .addGroup(JbodyLayout.createSequentialGroup()
                                .addComponent(jLabel32, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(18, 18, 18)))
                        .addGroup(JbodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(JbodyLayout.createSequentialGroup()
                                .addComponent(rdbHDNCC2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(rdbUnHDNCC2))
                            .addComponent(txtSDTNXB5, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(JbodyLayout.createSequentialGroup()
                        .addGroup(JbodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(JbodyLayout.createSequentialGroup()
                                .addComponent(jLabel29, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txtTenNXB2, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(JbodyLayout.createSequentialGroup()
                                .addGroup(JbodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel28, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(JbodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtSDTNXB4, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtDiachiNXB4, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(JbodyLayout.createSequentialGroup()
                                        .addComponent(rdbHDNXB2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(rdbUnHDNXB2)))))
                        .addGap(38, 38, 38)
                        .addComponent(btnInsertNXB2)
                        .addGap(18, 18, 18)
                        .addComponent(btnCleanNXB2, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31)
                        .addComponent(btnUpdateNXB2, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(JbodyLayout.createSequentialGroup()
                        .addGroup(JbodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel30, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel31, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(JbodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtDiachiNXB5, javax.swing.GroupLayout.DEFAULT_SIZE, 217, Short.MAX_VALUE)
                            .addComponent(txtTenNCC2))
                        .addGroup(JbodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(JbodyLayout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(btnInsert6, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnUpdate6, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JbodyLayout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(btnClean6, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnDelete6, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(136, Short.MAX_VALUE))
            .addComponent(jScrollPane9)
            .addComponent(jScrollPane6)
        );
        JbodyLayout.setVerticalGroup(
            JbodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JbodyLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(JbodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(JbodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnInsertNXB2)
                        .addComponent(btnCleanNXB2)
                        .addComponent(btnUpdateNXB2))
                    .addGroup(JbodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel29)
                        .addComponent(txtTenNXB2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(JbodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtDiachiNXB4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel28))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(JbodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel27)
                    .addComponent(txtSDTNXB4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(JbodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel26, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(rdbHDNXB2)
                    .addComponent(rdbUnHDNXB2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(JbodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTenNCC2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel30)
                    .addComponent(btnInsert6)
                    .addComponent(btnUpdate6))
                .addGap(18, 18, 18)
                .addGroup(JbodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel31)
                    .addComponent(txtDiachiNXB5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnClean6)
                    .addComponent(btnDelete6))
                .addGap(18, 18, 18)
                .addGroup(JbodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel32, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSDTNXB5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(JbodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rdbHDNCC2)
                    .addComponent(rdbUnHDNCC2)
                    .addComponent(jLabel33))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 335, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Jbody, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Jbody, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        add(jPanel2, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void rdbHDNXB2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdbHDNXB2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdbHDNXB2ActionPerformed

    private void rdbUnHDNXB2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdbUnHDNXB2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdbUnHDNXB2ActionPerformed

    private void txtSDTNXB4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSDTNXB4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSDTNXB4ActionPerformed

    private void txtDiachiNXB4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDiachiNXB4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDiachiNXB4ActionPerformed

    private void txtTenNXB2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTenNXB2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTenNXB2ActionPerformed

    private void btnUpdateNXB2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateNXB2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnUpdateNXB2ActionPerformed

    private void txtTenNCC2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTenNCC2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTenNCC2ActionPerformed

    private void txtDiachiNXB5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDiachiNXB5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDiachiNXB5ActionPerformed

    private void txtSDTNXB5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSDTNXB5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSDTNXB5ActionPerformed

    private void rdbHDNCC2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdbHDNCC2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdbHDNCC2ActionPerformed

    private void btnInsert6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInsert6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnInsert6ActionPerformed

    private void btnUpdate6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdate6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnUpdate6ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Jbody;
    private javax.swing.JButton btnClean4;
    private javax.swing.JButton btnClean5;
    private javax.swing.JButton btnClean6;
    private javax.swing.JButton btnCleanNXB;
    private javax.swing.JButton btnCleanNXB1;
    private javax.swing.JButton btnCleanNXB2;
    private javax.swing.JButton btnDelete4;
    private javax.swing.JButton btnDelete5;
    private javax.swing.JButton btnDelete6;
    private javax.swing.JButton btnInsert4;
    private javax.swing.JButton btnInsert5;
    private javax.swing.JButton btnInsert6;
    private javax.swing.JButton btnInsertNXB;
    private javax.swing.JButton btnInsertNXB1;
    private javax.swing.JButton btnInsertNXB2;
    private javax.swing.JButton btnUpdate4;
    private javax.swing.JButton btnUpdate5;
    private javax.swing.JButton btnUpdate6;
    private javax.swing.JButton btnUpdateNXB;
    private javax.swing.JButton btnUpdateNXB1;
    private javax.swing.JButton btnUpdateNXB2;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JTable jTable4;
    private javax.swing.JTable jTable5;
    private javax.swing.JTable jTable6;
    private javax.swing.JRadioButton rdbHDNCC;
    private javax.swing.JRadioButton rdbHDNCC1;
    private javax.swing.JRadioButton rdbHDNCC2;
    private javax.swing.JRadioButton rdbHDNXB;
    private javax.swing.JRadioButton rdbHDNXB1;
    private javax.swing.JRadioButton rdbHDNXB2;
    private javax.swing.JRadioButton rdbUnHDNCC;
    private javax.swing.JRadioButton rdbUnHDNCC1;
    private javax.swing.JRadioButton rdbUnHDNCC2;
    private javax.swing.JRadioButton rdbUnHDNXB;
    private javax.swing.JRadioButton rdbUnHDNXB1;
    private javax.swing.JRadioButton rdbUnHDNXB2;
    private javax.swing.JTable tblNCC;
    private javax.swing.JTable tblNCC1;
    private javax.swing.JTable tblNCC2;
    private javax.swing.JTextField txtDiachiNXB;
    private javax.swing.JTextField txtDiachiNXB1;
    private javax.swing.JTextField txtDiachiNXB2;
    private javax.swing.JTextField txtDiachiNXB3;
    private javax.swing.JTextField txtDiachiNXB4;
    private javax.swing.JTextField txtDiachiNXB5;
    private javax.swing.JTextField txtSDTNXB;
    private javax.swing.JTextField txtSDTNXB1;
    private javax.swing.JTextField txtSDTNXB2;
    private javax.swing.JTextField txtSDTNXB3;
    private javax.swing.JTextField txtSDTNXB4;
    private javax.swing.JTextField txtSDTNXB5;
    private javax.swing.JTextField txtTenNCC;
    private javax.swing.JTextField txtTenNCC1;
    private javax.swing.JTextField txtTenNCC2;
    private javax.swing.JTextField txtTenNXB;
    private javax.swing.JTextField txtTenNXB1;
    private javax.swing.JTextField txtTenNXB2;
    // End of variables declaration//GEN-END:variables
}
