CREATE database QLBHSACH
GO
USE QLBHSACH
GO
CREATE TABLE NHANVIEN
(
 MANV int IDENTITY(1,1) NOT NULL,
 TENNV NVARCHAR(50) NULL,
 MATKHAU NVARCHAR(50)  NULL,
 GIOITINH BIT NULL,
 TUOI INT NULL,
 DIACHI NVARCHAR(50) NULL,
 SDT VARCHAR(15) NULL,
 TRANGTHAI INT NULL
 
 CONSTRAINT PK_MANV PRIMARY KEY (MANV)
)
go
CREATE TABLE VAITRO
(
IDVAITRO int IDENTITY(1,1) NOT NULL,
VAITRO BIT NOT NULL,
MANV INT NOT NULL,
TENNV NVARCHAR(50) NOT NULL,
CALAMVCTU TIME NULL,
CALAMVCDEN TIME NULL,
TRANGTHAI BIT null,

CONSTRAINT PK_VAITRO PRIMARY KEY (IDVAITRO),
CONSTRAINT FK_VAITRO_MANV FOREIGN KEY (MANV) REFERENCES NHANVIEN,
)
GO
CREATE TABLE KHACHHANG
(
	MAKH	int IDENTITY(1,1) NOT NULL,
	TENKH	NVARCHAR(50) NULL,
	GIOITINH bit NULL,
	SDT		VARCHAR(15) NULL,
	GHICHU NVARCHAR(100) NULL,
	TRANGTHAI INT NULL,
CONSTRAINT PK_KHACHHANG PRIMARY KEY(MAKH),
)
GO
CREATE TABLE NGONNGU
(
MANN VARCHAR(20) NOT NULL,
LOAINN NVARCHAR(30)  NULL,
TRANGTHAI INT NULL,
CONSTRAINT PK_NGONNGU PRIMARY KEY (MANN)
)
go
CREATE TABLE NHACUNGCAP
(
 TENNHACUNGCAP NVARCHAR(50) NOT NULL,
 DIACHI NVARCHAR(100) NULL,
 SDT VARCHAR(15) NULL,
 TRANGTHAI INT NULL
 CONSTRAINT PK_NHACUNGCAP PRIMARY KEY (TENNHACUNGCAP)
)
GO
CREATE TABLE NHAXUATBAN
(
 TENNHAXUATBAN NVARCHAR(50) NOT NULL,
 DIACHI NVARCHAR(100) NULL,
 SDT VARCHAR(15) NULL,
 TRANGTHAI INT NULL
 CONSTRAINT PK_NHAXUATBAN PRIMARY KEY (TENNHAXUATBAN),
)
GO
CREATE TABLE VITRI
(
MAVITRI int IDENTITY(1,1) NOT NULL,
TENHANG NVARCHAR(20) NULL,
TRANGTHAI INT NULL
CONSTRAINT PK_MAVITRI PRIMARY KEY (MAVITRI),
)
CREATE TABLE DOTUOI
(
MADTUOI int IDENTITY(1,1) NOT NULL,
DOTUOI NVARCHAR(10)  NULL,
TRANGTHAI INT NULL,
CONSTRAINT PK_MADTUOI PRIMARY KEY (MADTUOI),
)
GO
CREATE TABLE LOAIBIA
(
MALB int IDENTITY(1,1) NOT NULL,
TENLB NVARCHAR(10)  NULL,
TRANGTHAI INT NULL,
CONSTRAINT PK_LOAIBIA PRIMARY KEY (MALB),
)
GO
CREATE TABLE HINHTHUC
(
MAHINHTHUC NVARCHAR(20) NOT NULL,
KIEUSACH NVARCHAR(50) NULL,
TRANGTHAI INT NOT NULL
CONSTRAINT PK_HINHTHUC PRIMARY KEY (MAHINHTHUC)
)
GO
IF OBJECT_ID('TACGIA') IS NOT NULL
	DROP TABLE TACGIA
GO
CREATE TABLE TACGIA
(
	MATG	int IDENTITY(1,1) NOT NULL,
	TENTG	NVARCHAR(50) NULL,
	BUTDANH	NVARCHAR(50) NULL,
	DIACHI	NVARCHAR(50) NULL,
	TRANGTHAI INT NULL
	CONSTRAINT PK_TACGIA PRIMARY KEY (MATG),	
)
GO
CREATE TABLE SACH
(
	MASACH	NVARCHAR(10) NOT NULL,
	TIEUDE	NVARCHAR(50) NULL,
	TENNHAXUATBAN NVARCHAR(50) NOT NULL,
	TONGLUONGSACH INT NOT NULL,
	TRANGTHAI INT NULL,
	CONSTRAINT PK_SACH PRIMARY KEY (MASACH),
	CONSTRAINT FK_SACH_TENNHAXUATBAN FOREIGN KEY (TENNHAXUATBAN) REFERENCES NHAXUATBAN,
)
GO
IF OBJECT_ID('THELOAI') IS NOT NULL
	DROP TABLE THELOAI
GO
CREATE TABLE THELOAI
(
	MATL	int IDENTITY(1,1) NOT NULL,
	TENTL	NVARCHAR(50) NULL,
	MAVITRI INT NULL,
	TRANGTHAI BIT NULL,
	CONSTRAINT PK_THELOAI PRIMARY KEY (MATL),
	CONSTRAINT FK_THELOAI_VITRI FOREIGN KEY (MAVITRI) REFERENCES VITRI,
)
GO
CREATE TABLE THELOAISACH
(
MATLS INT IDENTITY(1,1) NOT NULL,
MATL INT NULL,
MASACH NVARCHAR(10) NULL,
TENTL NVARCHAR(30) NULL,
TRANGTHAI INT NULL,
    CONSTRAINT PK_THELOAISACH PRIMARY KEY (MATLS),
	CONSTRAINT FK_THELOAISACH_THELOAI FOREIGN KEY (MATL) REFERENCES THELOAI,
	CONSTRAINT FK_THELOAISACH_SACH FOREIGN KEY (MASACH) REFERENCES SACH,
)
GO

CREATE TABLE CHITIETSACH
(
MACTS int IDENTITY(1,1) NOT NULL,
MASACH	NVARCHAR(10) NOT NULL,
GIA FLOAT NULL,
SOLUONG INT NOT NULL,
SOTRANG INT NULL,
HINH NVARCHAR(50) NOT NULL,
MAHINHTHUC NVARCHAR(20) NOT NULL,
TENNHACUNGCAP NVARCHAR(50) NOT NULL,
MALB INT NULL,
MADTUOI int NULL,
MANN VARCHAR(20)  NULL,
TRANGTHAI INT NOT NULL
CONSTRAINT PK_CHITIETSACH PRIMARY KEY (MACTS),
CONSTRAINT FK_CHITIETSACH_DOTUOI FOREIGN KEY (MADTUOI) REFERENCES DOTUOI,
CONSTRAINT FK_CHITIETSACH_NGONNGU FOREIGN KEY (MANN) REFERENCES NGONNGU,
CONSTRAINT FK_CHITIETSACH_LOAIBIA FOREIGN KEY (MALB) REFERENCES LOAIBIA,
CONSTRAINT FK_CHITIETSACH_SACH FOREIGN KEY (MASACH) REFERENCES SACH,
CONSTRAINT FK_CHITIETSACH_NHACUNGCAP FOREIGN KEY (TENNHACUNGCAP) REFERENCES NHACUNGCAP,
CONSTRAINT FK_CHITIETSACH_HINHTHUC FOREIGN KEY (MAHINHTHUC) REFERENCES HINHTHUC,
)
GO
CREATE TABLE TACGIACHITIET
(
MATGCT int IDENTITY(1,1) NOT NULL,
MATG INT NULL,
MACTS INT NULL,
TRANGTHAI INT NOT NULL
CONSTRAINT PK_TACGIACHITIET PRIMARY KEY (MATGCT),
CONSTRAINT FK_TACGIACHITIET_TACGIA FOREIGN KEY (MATG) REFERENCES TACGIA,
CONSTRAINT FK_TACGIACHITIET_CHITIESACH FOREIGN KEY (MACTS) REFERENCES CHITIETSACH,
)
GO
CREATE TABLE HOADON
(
 MAHD int IDENTITY(1,1) NOT NULL,
 MAKH int  NOT NULL,
 MANV INT NOT NULL,
 TONGSOLUONG INT NULL,
 TONGTIEN MONEY NULL,
 NGAYMUA DATETIME NULL,
 GHICHU NVARCHAR(100) NULL,
 TRANGTHAI int NULL
 CONSTRAINT PK_MAHD PRIMARY KEY (MAHD),
 CONSTRAINT fk_HOADON_MAKH FOREIGN KEY (MAKH) REFERENCES KHACHHANG,
 CONSTRAINT FK_HOADON_MANV FOREIGN KEY (MANV) REFERENCES NHANVIEN
)
GO

CREATE TABLE CTHOADON
( 
 MACTHD int IDENTITY(1,1) NOT NULL,
 MACTS	INT NOT NULL,
 MAHD INT NOT NULL,
 GIABAN MONEY NULL,
 SL INT NULL,
 TIEUDE	NVARCHAR(50) NULL,
 GHICHU NVARCHAR(100) NULL,
 TRANGTHAI INT NOT NULL
 CONSTRAINT PK_CTHOADON PRIMARY KEY (MACTHD),
 CONSTRAINT FK_CTHOADON_HOADON FOREIGN KEY (MAHD) REFERENCES HOADON,
 CONSTRAINT FK_CTHOADON_CHITIETSACH FOREIGN KEY (MACTS) REFERENCES CHITIETSACH
)

select T.TENTL,SUM(A.SL) From CTHOADON A JOIN CHITIETSACH B ON A.MACTS = B.MACTS 
JOIN SACH C ON C.MASACH = B.MASACH JOIN THELOAISACH D ON D.MASACH = C.MASACH JOIN THELOAI T
ON T.MATL = D.MATL GROUP BY T.TENTL

select 
		YEAR(E.NGAYMUA) NAM,
		T.TENTL TENTHELOAI,
		SUM(SL) SOLUONG,
		SUM(TONGTIEN) TONGTIEN
	From HOADON E JOIN  CTHOADON A on E.MAHD = A.MAHD JOIN CHITIETSACH B ON A.MACTS = B.MACTS 
		JOIN SACH C ON C.MASACH = B.MASACH 
		JOIN THELOAISACH D ON D.MASACH = C.MASACH 
		JOIN THELOAI T
	ON T.MATL = D.MATL 
	WHERE YEAR(NGAYMUA) = 2021
	GROUP BY YEAR(E.NGAYMUA),T.TENTL